# ============================================================================
# PROJECT.yaml - Archivo de metadatos del proyecto
# ============================================================================
#
# PARA CLAUDE (IA): Este archivo es leido por el Project Manager (99999) para:
#   1. Detectar el estado del proyecto (online/offline)
#   2. Saber que puertos monitorear
#   3. Entender la arquitectura del proyecto
#
# INSTRUCCIONES PARA CLAUDE:
#   - Si haces cambios de version, actualiza 'project.version'
#   - Siempre actualiza 'updated_at' y 'updated_by' al modificar
#   - El 'updated_by' debe ser tu identificador (ej: claude-993)
#
# NO MODIFICAR SIN RAZON:
#   - project.code (identificador unico)
#   - server.location (donde corre el proyecto)
#   - server.base_path (ruta del proyecto)
#
# ============================================================================

project:
  code: web25-993
  name: Prompts para Negocios
  version: 0.3.0
  status: development
  description: Sistema de evaluacion de negocios con fase de descubrimiento de nichos (P0-P5)

# Evaluacion activa
active_evaluation:
  name: Shopify Integrations Global (LATAM + Europa)
  folder: shopify-integrations-global
  stage: P0-complete
  source: debate-multi-ia-2026-02-05
  debate_ticket: 256
  debate_participants: deepseek-chat, gpt-5.1
  nichos_identificados: 4
  nichos_con_consenso: 4
  consensus_threshold: 0.80
  nicho_prioritario: PayReconX (Conciliacion de Pagos Multi-metodo)
  ice_score_top: 820
  next_step: Ejecutar P1 en PayReconX
  mercado_inicial: LATAM (Brasil, Mexico)

  # Nichos identificados por debate (P0)
  p0_nichos:
    - nicho: "#1 PayReconX"
      tipo: Conciliacion Pagos Multi-metodo
      ice_score: 820
      decision: VALIDAR PRIMERO
      mercado: LATAM -> Europa
    - nicho: "#2 ReturnFlow CX"
      tipo: Devoluciones & Re-commerce
      ice_score: 730
      decision: VALIDAR
      mercado: Europa -> LATAM
    - nicho: "#3 TaxRules Hub"
      tipo: Motor Fiscal por Pais/Estado
      ice_score: 680
      decision: RESERVA
      mercado: LATAM -> Europa
    - nicho: "#4 FinLink DTC"
      tipo: Finanzas Alternativas/Factoring
      ice_score: 780
      decision: RESERVA CONDICIONAL
      mercado: LATAM -> Europa

# Evaluacion pendiente
pending_evaluation:
  name: clinica-bot (WhatsApp IA para Consultorios Medicos)
  folder: clinica-bot
  stage: P1-in-progress
  source: producto-existente-web26-056-v0.13.0
  tipo: producto-pre-construido
  next_step: Completar desk research P1
  mercado_inicial: Mexico (consultorios independientes)
  tam: 157533 consultorios medicos/dentales (INEGI DENUE 2025)
  sam: 12600 consultorios WhatsApp-activos con disposicion a pagar
  relacion_crm48: nicho Clinicas/Dentistas identificado en crm48/00-idea-inicial.md

# Evaluacion anterior (completada)
previous_evaluation:
  name: Shopify Custom Dev Europa
  folder: shopify-custom-dev-europa
  stage: P1-complete
  nichos_identificados: 5
  nichos_evaluados_p1: 5
  nichos_proceder: 1
  nichos_no_proceder: 2
  nichos_descartados: 1
  nichos_reserva_condicional: 1
  nicho_prioritario: German E-Invoice Butler (ZUGFeRD/XRechnung)
  p1_score: 7.3
  p1_decision: Proceder con experimento
  next_step: Experimento validacion (landing + ads 14 dias)
  blocker_p2: Resultados experimento

  # Evaluaciones P1 completadas (5/5 = 100%)
  p1_evaluations:
    - nicho: "#1 ZUGFeRD Butler"
      score: 7.3
      decision: PROCEDER
    - nicho: "#2 VAT Automation"
      score: 4.8
      decision: NO PROCEDER
    - nicho: "#3 ERP Connector"
      score: 4.2
      decision: NO PROCEDER
    - nicho: "#4 Carrier Aggregator"
      score: 3.5
      decision: DESCARTADO
      razon: "Packlink PRO gratis 4.9/5 723 reviews"
    - nicho: "#5 Factur-X France"
      score: 5.8
      decision: RESERVA CONDICIONAL
      razon: "Depende exito de #1, 80% codigo compartido"

server:
  location: wsl
  base_path: /mnt/c/Users/abela/prweb/web25-993-prompts-para-negocios

service:
  type: none
  expect_offline: true

urls:
  repository: https://gitlab.com/abelardodiaz/web25-993-prompts-para-negocios

stack:
  primary: documentation

updated_at: "2026-02-08T12:00:00Z"
updated_by: claude-993

# Skills creados (fuera del proyecto, en ~/.claude/skills/)
skills_created:
  - name: landing-builder
    path: ~/.claude/skills/landing-builder/
    description: Agente autonomo para crear landing pages anti-AI-slop
    files:
      - SKILL.md (146 lines)
      - references/anti-slop-rules.md (317 lines)
      - references/style-presets.md (196 lines)
      - examples/editorial-germanica.html (914 lines)
